pub const SIGNAL_DISPLAY_FLAGS: &str = "SIGNAL_DISPLAY_FLAGS";

pub const SIGNAL_LOGGER_LEVEL: &str = "SIGNAL_LOGGER_LEVEL";
pub const SIGNAL_ONSCREEN_LOGGER: &str = "SIGNAL_ONSCREEN_LOGGER";
pub const SIGNAL_ENABLE_LOGGER: &str = "SIGNAL_ENABLE_LOGGER";

pub const SIGNAL_CONFIG_DIR: &str = "SIGNAL_CONFIG_DIR";
pub const ACCOUNTS_DIR: &str = "ACCOUNTS_DIR";
